version: '3.4'

services:
  backend:
    image: node:14.5-alpine3.12
    working_dir: /app/backend
    volumes:
      - ./:/app/backend:rw
    ports:
      - "9000:9000"
    command: tail -f /dev/null
